--- 

# tasks file for cert_selfsigned 
- name: Install requirement for generate cert_selfsigned

  block:

  - name: install python3 and pip3
    apt:
      name: "{{item}}"
      state: present
    with_items:
    - python3
    - python3-pip
    when: ansible_os_family == 'Debian'

  - name: pip install cryptography
    pip:
      name: cryptography

- name: Generate self-signed certificate on localhost 

  block: 

  - name: Generate an OpenSSL private key with the default values (4096 bits, RSA) 
    openssl_privatekey: 
      path: "/tmp/{{ cert_pkey_name }}" 

  - name: Generate the CSR file signed with the private key 
    openssl_csr: 
      path: "/tmp/{{ cert_req_name }}" 
      privatekey_path: "/tmp/{{ cert_pkey_name }}" 
      country_name: "{{ cert_country_name }}" 
      organization_name: "{{ cert_organization_name }}" 
      email_address: "{{ cert_email_address }}" 
      common_name: "{{ cert_cname }}" 

  - name: Sign the CSR file as a CA to turn it into a certificate 
    openssl_certificate: 
      path: "/tmp/{{ cert_crt_name }}" 
      privatekey_path: "/tmp/{{ cert_pkey_name }}" 
      csr_path: "/tmp/{{ cert_req_name }}" 
      provider: selfsigned 


  - name: Copy keys to the remote host 
    copy: 
      src: "{{ item.s }}" 
      dest: "{{ item.d }}" 
      mode: "{{ item.m }}" 
      force: no
      remote_src: yes
    with_items: 
    - { s: "/tmp/{{ cert_pkey_name }}", d: "/etc/ssl/private", m: '640' } 
    - { s: "/tmp/{{ cert_crt_name }}", d: "/etc/ssl/certs", m: '644' } 